import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/common/navbar/Navbar';
import Footer from '@/components/common/footer/Footer';
import { NextAuthProvider } from './providers/sessionProviders';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        {/* Add Cloudinary's upload widget script */}
        <script
          type="text/javascript"
          src="https://upload-widget.cloudinary.com/global/all.js"
          async
        ></script>
        <link
          href="https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&family=Georgia&family=Times+New+Roman&family=Playfair+Display:wght@400;700&family=Crimson+Pro:wght@400;700&family=Roboto:wght@400;500;700&family=Lato:wght@400;700&family=Helvetica+Neue&family=Open+Sans:wght@400;700&family=Montserrat:wght@400;700&family=Bebas+Neue&family=Oswald:wght@400;500&family=Cinzel:wght@400;700&family=Raleway:wght@400;500;600&family=Dancing+Script&family=Pacifico&family=Great+Vibes&family=Lobster&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <div>
          <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="/apple-touch-icon.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="/favicon-32x32.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="/favicon-16x16.png"
          />
          <link rel="manifest" href="/site.webmanifest" />
        </div>
        <NextAuthProvider>
          <Navbar />
          {children}
        </NextAuthProvider>
        <Footer />
      </body>
    </html>
  );
}
